version: "3.3"

services:
  app:
    build:
      context: .
    container_name: api
    ports:
      - 8100:8080
    volumes:
      - db-data:/app
    depends_on:
      - db
    networks:
      - teste       
  db:
    image: 'mariadb:10.9.1-rc-jammy'
    container_name: db
    ports:
      - 15432:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=gerenciador
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    networks:
      - teste

volumes:
  db-data:

networks:
    teste:
        driver: bridge
